# fly.toml app configuration file generated for wispy-feather-7821 on 2024-02-29T09:03:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wispy-feather-7821'
primary_region = 'lhr'

[build]
  dockerfile = 'apps/api/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
